// One-way compiler: Doc (our AST) -> Typst source string.
//
// This is the heart of the "own the model" approach. Everything the UI does is
// just editing the Doc; rendering and export both go through here.

import type { Block, Doc, DocStyle, LetBinding, PageSize } from './model';

const PAPER: Record<PageSize, string> = {
  a4: 'a4',
  'us-letter': 'us-letter',
  a5: 'a5',
};

/** Escape text destined for Typst MARKUP mode so it renders literally. */
export function escapeMarkup(s: string): string {
  // Order matters: backslash first.
  return s.replace(/([\\#$*_`<>@~])/g, '\\$1');
}

/** Quote a string for Typst CODE mode (string literal). */
function quote(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

function genStyle(style: DocStyle): string {
  const lines: string[] = [];
  lines.push(`#set page(paper: ${quote(PAPER[style.page.paper])}, margin: ${style.page.marginCm}cm)`);

  const textArgs: string[] = [`size: ${style.text.sizePt}pt`];
  if (style.text.font.trim() !== '') {
    textArgs.unshift(`font: ${quote(style.text.font.trim())}`);
  }
  lines.push(`#set text(${textArgs.join(', ')})`);

  lines.push(
    `#set par(leading: ${style.par.leadingEm}em, justify: ${style.par.justify ? 'true' : 'false'})`,
  );
  return lines.join('\n');
}

function genLet(b: LetBinding): string {
  const name = b.name.trim() || 'unnamed';
  if (b.kind === 'value') {
    return `#let ${name} = ${b.code.trim() || '""'}`;
  }
  // component: receives `body`
  return `#let ${name}(body) = {\n${indent(b.code.trim() || 'body', 2)}\n}`;
}

function indent(s: string, n: number): string {
  const pad = ' '.repeat(n);
  return s
    .split('\n')
    .map((l) => (l.length ? pad + l : l))
    .join('\n');
}

function genBlock(b: Block): string {
  switch (b.type) {
    case 'heading':
      return `${'='.repeat(b.level)} ${escapeMarkup(b.text)}`;
    case 'paragraph':
      return escapeMarkup(b.text);
    case 'list':
      return b.items
        .map((it) => `${b.ordered ? '+' : '-'} ${escapeMarkup(it)}`)
        .join('\n');
    case 'callout':
      // Invokes the built-in `callout` component (see BUILTIN_LETS).
      return `#callout[${escapeMarkup(b.text)}]`;
    case 'raw':
      return b.code; // verbatim — the escape hatch
  }
}

/**
 * A component every document gets for free, so the "Callout" content block has
 * something to call. In the real product these live in the template library.
 */
export const BUILTIN_LETS = `#let callout(body) = block(
  fill: rgb("#eef2ff"),
  stroke: 0.5pt + rgb("#6366f1"),
  inset: 10pt,
  radius: 4pt,
  width: 100%,
)[#body]`;

export function generate(doc: Doc): string {
  const parts: string[] = [];
  parts.push('// Generated by typst-wysiwyg — do not hand-edit (yet).');
  parts.push(genStyle(doc.style));
  parts.push('');
  parts.push(BUILTIN_LETS);
  if (doc.lets.length) {
    parts.push('');
    parts.push('// --- user definitions ---');
    parts.push(doc.lets.map(genLet).join('\n'));
  }
  parts.push('');
  parts.push('// --- content ---');
  // Blank line between blocks => Typst paragraph breaks.
  parts.push(doc.content.map(genBlock).join('\n\n'));
  parts.push('');
  return parts.join('\n');
}
