// Combine the logic layer (#set / #let / #show) with the serialized ProseMirror
// content into a full Typst source string. One-way only.

import type { Node as PMNode } from '@tiptap/pm/model';
import type { DocLogic, DocStyle, LetBinding, PageSize, ShowRule } from './model';
import { serializeContent, escapeMarkup } from './serialize';

const PAPER: Record<PageSize, string> = { a4: 'a4', 'us-letter': 'us-letter', a5: 'a5' };

function quote(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

/** A hex color like #1c7ed6 -> rgb("#1c7ed6"); anything else passed through. */
function color(v: string): string {
  const t = v.trim();
  return /^#[0-9a-fA-F]{3,8}$/.test(t) ? `rgb(${quote(t)})` : t;
}

function genStyle(style: DocStyle): string {
  const lines: string[] = [];
  const pageArgs: string[] = [`paper: ${quote(PAPER[style.page.paper])}`, `margin: ${style.page.marginCm}cm`];
  if (style.page.numbering) pageArgs.push(`numbering: "1"`);
  if (style.page.header?.trim()) pageArgs.push(`header: [${escapeMarkup(style.page.header.trim())}]`);
  if (style.page.footer?.trim()) pageArgs.push(`footer: [${escapeMarkup(style.page.footer.trim())}]`);
  lines.push(`#set page(${pageArgs.join(', ')})`);
  const textArgs: string[] = [`size: ${style.text.sizePt}pt`];
  if (style.text.font.trim() !== '') textArgs.unshift(`font: ${quote(style.text.font.trim())}`);
  lines.push(`#set text(${textArgs.join(', ')})`);
  lines.push(`#set par(leading: ${style.par.leadingEm}em, justify: ${style.par.justify})`);
  return lines.join('\n');
}

function genLet(b: LetBinding): string {
  const name = b.name.trim() || 'unnamed';
  if (b.kind === 'value') return `#let ${name} = ${b.code.trim() || '""'}`;
  const body = (b.code.trim() || 'body')
    .split('\n')
    .map((l) => (l.length ? '  ' + l : l))
    .join('\n');
  return `#let ${name}(body) = {\n${body}\n}`;
}

function genShow(s: ShowRule): string {
  let selector = s.target as string;
  if (s.target === 'heading' && s.level != null) selector = `heading.where(level: ${s.level})`;

  const props: string[] = [];
  if (s.props.fill.trim()) props.push(`fill: ${color(s.props.fill)}`);
  if (s.props.sizePt != null) props.push(`size: ${s.props.sizePt}pt`);
  if (s.props.weight !== 'inherit') props.push(`weight: ${quote(s.props.weight)}`);
  if (s.props.style !== 'inherit') props.push(`style: ${quote(s.props.style)}`);

  // Nothing to set => emphasize visibly so the rule is never a no-op surprise.
  const body = props.length ? `set text(${props.join(', ')})` : 'set text()';
  return `#show ${selector}: ${body}`;
}

export const BUILTIN_LETS = `#let callout(body) = block(
  fill: rgb("#eef2ff"),
  stroke: 0.5pt + rgb("#6366f1"),
  inset: 10pt,
  radius: 4pt,
  width: 100%,
)[#body]`;

export function generate(logic: DocLogic, content: PMNode): string {
  const parts: string[] = [];
  parts.push('// Generated by typst-wysiwyg — do not hand-edit (yet).');
  parts.push(genStyle(logic.style));
  parts.push('');
  parts.push(BUILTIN_LETS);

  if (logic.lets.length) {
    parts.push('');
    parts.push('// --- definitions ---');
    parts.push(logic.lets.map(genLet).join('\n'));
  }
  if (logic.shows.length) {
    parts.push('');
    parts.push('// --- show rules ---');
    parts.push(logic.shows.map(genShow).join('\n'));
  }

  parts.push('');
  parts.push('// --- content ---');
  parts.push(serializeContent(content));
  parts.push('');
  return parts.join('\n');
}
